config/routes.rb
StockMgr::Application.routes.draw do
  devise_for :users
  resources :items
  root "items#index"

  get "/items_record_sale" => "items#record_sale"
  post "/items_record_sale" => "items#record_sale"

  get "/items_add_stock" => "items#add_stock"
  post "/items_add_stock" => "items#add_stock"

  get "/items_update_stock" => "items#update_stock"
  post "/items_update_stock" => "items#update_stock"

  get "/items_update_purchases" => "items#update_purchases"
  post "/items_update_purchases" => "items#update_purchases"

  

end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :name, presence: true
	validates :qty_current, presence: true
	validates :qty_ideal, presence: true
	validates :exp_date, presence: true
	validates :qty_sold, presence: true
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /items
  # GET /items.json
  def index
    @on_index_page = true
    @items = current_user.items.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = current_user.items.new
  end

  # GET /items/1/edit
  def edit
  end

  def record_sale
    @items = current_user.items.all
  end

  def add_stock
    @items = current_user.items.all
  end

  def update_stock
    current_user.items.update(params[:items].keys, params[:items].values)
    current_user.items.all.each do |i|
      if i.days
        i.days = i.days + 1
      else
        i.days = 1
      end
      i.avg_sales = i.avg_sales + (i.sold_today / i.days)
      i.qty_current = i.qty_current - i.sold_today
      i.qty_sold = i.qty_sold + i.sold_today
      i.save
    end
    flash[:notice] = "Sales added. "
    redirect_to items_url
  end


  def update_purchases
    current_user.items.update(params[:items].keys, params[:items].values)
    current_user.items.all.each do |i|
      i.bought_today ||= 0
      i.qty_current = i.qty_current + i.bought_today
      i.save
    end
    flash[:notice] = "New stock registered. "
    redirect_to items_url
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'You Successfully added a new Item.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = current_user.items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :details, :qty_current, :qty_ideal, :sold_today, :qty_sold, :avg_sales, :supplier, :exp_date, :pur_date, :bought_today)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for @item, :html => { :class => 'form-horizontal' } do |f| %>
  <% val = nil %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <% val = @item.name %>
      <% val ||= "" %>
      <%= f.text_field :name, :class => 'text_field form-control', :value => val %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <% val = @item.price %>
      <% val ||= 0 %>
      <%= f.text_field :price, :class => 'text_field', :value => val %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :details, :class => 'control-label' %>
    <div class="controls">
      <% val = @item.details %>
      <% val ||= "" %>
      <%= f.text_field :details, :class => 'text_field', :value => val %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :qty_current, :class => 'control-label' %>
    <div class="controls">
      <% val = @item.qty_current %>
      <% val ||= 0 %>
      <%= f.text_field :qty_current, :class => 'text_field', :value => val%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :qty_ideal, :class => 'control-label' %>
    <div class="controls">
      <% val = @item.qty_ideal %>
      <% val ||= 0 %>
      <%= f.text_field :qty_ideal, :class => 'text_field', :value => val %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :qty_sold, :class => 'control-label' %>
    <div class="controls">
      <% val = @item.qty_sold %>
      <% val ||= 0 %>
      <%= f.text_field :qty_sold, :class => 'text_field', :value => val %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :avg_sales, :class => 'control-label' %>
    <div class="controls">
      <% val = @item.avg_sales %>
      <% val ||= 0 %>
      <%= f.text_field :avg_sales, :class => 'text_field', :value => val %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :supplier, :class => 'control-label' %>
    <div class="controls">
      <% val = @item.supplier %>
      <% val ||= "" %>
      <%= f.text_field :supplier, :class => 'text_field', :value => val %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :exp_date, :class => 'control-label' %>
    <div class="controls">
      <% val = @item.exp_date %>
      <% val ||= Date.today + 30.days %>
      <%= f.text_field :exp_date, :class => 'text_field', :value => val %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :pur_date, :class => 'control-label' %>
    <div class="controls">
      <% val = @item.pur_date %>
      <% val ||= Date.today %>
      <%= f.text_field :pur_date, :class => 'text_field', :value => val %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                items_path, :class => 'btn' %>
  </div>
<% end %>

app/views/items/add_stock.html.erb
<h1>New Stock</h1>
<% if !(@items.empty?) %>
	<h4>Please enter how many of each Item you bought today.</h4>
	<span class="text-danger"><p>* note that this must only be done ONCE a day.</p></span>
	<%= form_tag items_update_purchases_path, method: :post do %>
		<% @items.each do |item| %>
			<%= fields_for "items[]", item do |f| %>
				<div class="control-group">
	          		<h3><%= item.name %></h3>
	        		<div class="controls">
	      				<%= f.text_field :bought_today, :class => 'text_field' %>
	    			</div>
	  			</div>
			<% end %>
		<% end %>
		<%= submit_tag "Submit" %>
	<% end %>
<% else %>
	<h2>Tip:</h2><h4>You need to add items in "Item Management" before you can record their purchases!</h4>
<% end %>

app/views/items/edit.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/edit_multiple.html.erb
<h1>EDIT MULTIPLE</h1>
<% form_tag update_items_path, method: :get do %>


<% end %>

app/views/items/index.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1>Current Stock</h1>
</div>
<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th><b>Link</b></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:details) %></th>
      <th><b>Stock</b></th>
      <th><b>Sold</b></th>
      <th><b>Sales Avg</b></th>
      <th><b>Expiry</b></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to "View",
            item_path(item),
            :class => 'btn btn-mini btn-success' %></td>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= item.details %></td>
        <td><%= item.qty_current %></td>
        <td><%= item.qty_sold %></td>
        <td><%= item.avg_sales %></td>
        <td><%= item.exp_date.to_formatted_s(:short)  %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_item_path(item), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      item_path(item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<%= link_to "Add New Item",
            new_item_path,
            :class => 'btn btn-primary' %>

app/views/items/login_error.html.erb
<h1>login_error.html.erb</h1>

app/views/items/new.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1>Add <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<p>Required Fields: Name, Current and Ideal Quantities and Expiry Date</p>
<br />
<%= render :partial => 'form' %>

app/views/items/record_sale.html.erb
<h1>Sold Today</h1>
<% if !(@items.empty?) %>
	<h4>Please enter how many of each Item you sold today.</h4>
	<span class="text-danger"><p>* note that this must only be done ONCE a day.</p></span>
	<%= form_tag items_update_stock_path, method: :post do %>
		<% @items.each do |item| %>
			<%= fields_for "items[]", item do |f| %>
				<div class="control-group">
	          		<h3><%= item.name %></h3>
	        		<div class="controls">
	      				<%= f.text_field :sold_today, :class => 'text_field' %>
	    			</div>
	  			</div>
			<% end %>
		<% end %>
		<%= submit_tag "Submit" %>
	<% end %>
<% else %>
	<h2>Tip:</h2><h4>You need to add items in "Item Management" before you can record their sales!</h4>
<% end %>

app/views/items/show.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @item.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @item.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:details) %>:</strong></dt>
  <dd><%= @item.details %></dd>
  <dt><strong><%= model_class.human_attribute_name(:qty_current) %>:</strong></dt>
  <dd><%= @item.qty_current %></dd>
  <dt><strong><%= model_class.human_attribute_name(:qty_ideal) %>:</strong></dt>
  <dd><%= @item.qty_ideal %></dd>
  <dt><strong><%= model_class.human_attribute_name(:qty_sold) %>:</strong></dt>
  <dd><%= @item.qty_sold %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avg_sales) %>:</strong></dt>
  <dd><%= @item.avg_sales %></dd>
  <dt><strong><%= model_class.human_attribute_name(:supplier) %>:</strong></dt>
  <dd><%= @item.supplier %></dd>
  <dt><strong><%= model_class.human_attribute_name(:exp_date) %>:</strong></dt>
  <dd><%= @item.exp_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pur_date) %>:</strong></dt>
  <dd><%= @item.pur_date %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              items_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_path(@item), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_path(@item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pascal's Stock Manager" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <style type="text/css">
        body {
          padding-bottom: 80px;
          color: #5b5b5b;
        }

    </style>
  </head>
  <body>

    <div class="navbar navbar-fixed-top navbar-inverse row-fluid">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand navbar-link" href="#">Pascal's Stock Manager</a>
            <div class="container nav-collapse">
              <ul class="nav navbar-left pull-left">
                <li class="divider-vertical"></li>
                <li><%= link_to "Item Management", items_path  %></li>
                <li class="divider-vertical"></li>
                <li><%= link_to "Record Sale", items_record_sale_path  %></li>
                <li class="divider-vertical"></li>
                <li><%= link_to "Add Stock", items_add_stock_path  %></li>
              </ul>
              <ul class="nav pull-right navbar-right">
                <% if user_signed_in? %>
                  <li class='pull-right navbar-right'>
                  <%= link_to "Signed in as #{current_user.email} ", "#" %>
                  </li>
                  <li class="divider-vertical"></li>
                  <li class='pull-right navbar-right'>
                    <%= link_to "Logout", destroy_user_session_path, method: "delete" %>
                  </li>
              <% end %>
              </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <% if @on_index_page %>
          <div class="span3">
            <div class="well sidebar-nav pull-right">
              <h2>Messages</h2>
              <div id="check_stock_levels">
                <% 1.times do %>
                  <% error_counter = 0 %>
                  <% @items.each do |item| %>
                    <% if item.exp_date <= (Date.today + 7.days) %>
                      <% error_counter = error_counter + 1 %>
                      <% if item.exp_date <= (Date.today) %>
                        <div class="alert alert-danger alert-dismissable">
                          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                          <strong>Warning! </strong><%= item.name %> has expired!
                        </div>
                      <% else %>
                        <div class="alert alert-warning alert-dismissable">
                          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                          <strong>Warning! </strong><%= item.name %> will soon expire!
                        </div>
                      <% end %>
                    <% end %>
                    <% if item.qty_current <= (item.qty_ideal / 2)  %>
                      <% error_counter = error_counter + 1 %>
                      <div class="alert alert-info alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <strong>Notice: </strong> your stock of <%= item.name %> is lower than desired!
                      </div>
                    <% end %>
                  <% end %>
                  <% if error_counter == 0 %>
                      <div class="alert alert-success">
                        <strong>Congratulations: </strong> Everything is in order!
                      </div>
                    <% end %>
                <% end %>
              </div>
            </div><!--/.well -->
           
          </div><!--/span-->
           <% end %>
        </div><!--/row-->
      <br />
      <br />
      <br />
    </div> <!-- /container -->

<!-- FOOTER -->
    <nav id="footbar" class="navbar navbar-fixed-bottom navbar-inverse " role="navigation" >

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-inner">
    <div class="nav navbar-nav pull-right navbar-right">
      <ul class="nav">
      <li><a href="http://wilsonmaravilha.com">Wilson Maravilha - <%= Date.today.year %></a></li>
      <li class="divider-vertical"></li>
      <li><a href="http://wilsonmaravilha.com/contactme/">Tech Support</a></li>
    </ul>
    </div>
  </div><!-- /.navbar-collapse -->
</nav>
  </body>
</html>